### ISSUE TITLE
Migrate to JupyterLab v2

### ISSUE THREAD

**Issue by zmeecer** [IBM/jupyterlab-s3-browser#11]
Currently, the extension cannot be used with JupyterLab v2 (released 2 days ago)

https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html

**Comment by reevejd** [comment]
Thanks for opening the issue. [Version 0.4.0 is now available](https://github.com/IBM/jupyterlab-s3-browser/releases/tag/0.4.0) and is compatible with JupyterLab 2.0.
