### ISSUE TITLE
Can't install from the extension manager

### ISSUE THREAD

**Issue by paulperry** [IBM/jupyterlab-s3-browser#2]
Instead of following the install steps here, I chose to install from the Extension Manager and received this error:

```
This extension does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab            Extension              Package
>=4.0.0-alpha.1 <4.1.03.0.0                  @jupyterlab/coreutils
```

**Comment by reevejd** [comment]
Hello @paulperry,

Thanks for bringing the issue to my attention. This extension now supports the latest version of JupyterLab (1.2.3). Note that this extension has an accompanying server extension, so if you try to install it through the extension manager you'll get a warning: 
<img width="499" alt="Screen Shot 2019-11-25 at 2 50 27 PM" src="https://user-images.githubusercontent.com/12180828/69572880-0b27fa80-0f93-11ea-8175-19ca6c883116.png">
Before clicking OK you should install the server extension by running `pip install jupyterlab-s3-browser`.
