### ISSUE TITLE
Is there a way to specify credentials in configuration

### ISSUE THREAD

**Issue by jpays** [IBM/jupyterlab-s3-browser#27]
Hello, 

I'm using version 6.1 of the plugin.

I successfully installed the s3 browser in our environment, but I would like to save the users the pain of typing their credentials in the auth form.

It's not clear if there is a way to set the credentials (endpoint_url, access key and secret) in a configuration file and/or environment variables to entirely skip the auth form ?

Thank you

Jerome

**Comment by reevejd** [comment]
It's currently not supported, but I should be able to release a new version next week with support for environment variable-based authentication. Thanks for the suggestion.

**Comment by melvinev** [comment]
Hi @reevejd love the extension thank you.  Any update on timeline for auto login using environment variables?

**Comment by reevejd** [comment]
Hi @melvinev, thanks for your interest. I'll try to get it out by this Monday. It's not particularly difficult to do, I've just been busier than expected the past two weeks.

**Comment by reevejd** [comment]
I've added support for environment variable based authentication in ece9312cf592ec2f63f91fec6b239e924bc118d1. It's available in the newly released version 0.7.0.
