### ISSUE TITLE
Boto debug logging is too verbose

### ISSUE THREAD

**Issue by calvinytong** [IBM/jupyterlab-s3-browser#29]
**Is your feature request related to a problem? Please describe.**
The extension seems to dump the debug logs from botocore, which are pretty verbose and can hide other logs

**Describe the solution you'd like**
It would be nice to allow the logging to be configurable and/or set the default level to something less verbose (err/warn maybe)

**Comment by reevejd** [comment]
Thanks for opening the issue, sorry it took me so long to get around to it. Logging is no longer so verbose.

**Comment by calvinytong** [comment]
Thanks so much for getting to it!
