### ISSUE TITLE
Error right after installation

### ISSUE THREAD

**Issue by eric-leblouch-al** [IBM/jupyterlab-s3-browser#3]
When I reload the jupyter lab after the installation I have the following error:
```
s3/auth?xxxxxxxxxxxxx:1 Failed to load resource: the server responded with a status of 404 (Not Found)
lab:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
```

The s3 and s3/auth endpoints are not defined on the instance.

Is there a needed configuration prior to the reload in addition to the pip and jupyter labextension installations ?

**Comment by reevejd** [comment]
Hello, 

You may need to manually enable the server extension by running:
```
jupyter serverextension enable --py jupyterlab_s3_browser
```
Please let me know if that works for you and I'll make a note in the readme.

**Comment by eric-leblouch-al** [comment]
That was it thank you !

**Comment by reevejd** [comment]
Great! I'll add a note to the readme
