### ISSUE TITLE
Can not install on JupyterLab 3.0

### ISSUE THREAD

**Issue by haijohn** [IBM/jupyterlab-s3-browser#33]
**Describe the bug**
when install on jupyterlab 3.0 the following error occured:
```
An error occured.
ValueError: The extension "jupyterlab-s3-browser" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab                  Extension      Package
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0 @jupyterlab/apputils
>=5.0.0 <5.1.0              >=4.0.0 <5.0.0 @jupyterlab/coreutils
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0 @jupyterlab/docmanager
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0 @jupyterlab/filebrowser
>=6.0.0 <6.1.0              >=5.0.0 <6.0.0 @jupyterlab/services
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0 @jupyterlab/settingregistry
See the log file for details:  /tmp/jupyterlab-debug-8x6pskax.log
```
**To Reproduce**
```jupyter labextension install jupyterlab-s3-browser```

**Comment by octavd** [comment]
I think this extension is abandoned. :(

**Comment by reevejd** [comment]
Thanks for opening the issue. I definitely want to support JupyterLab 3, but I haven't had time to work on it yet. I'll try to release a 3.x compatible version sometime this weekend.

**Comment by reevejd** [comment]
The upgrade process requires more effort than I expected, so it will likely take another week or two before I find time to finish it.

**Comment by av8r** [comment]
any news ?

**Comment by reevejd** [comment]
I should be able to put out a release candidate version tomorrow for anyone who's interested to try. Then probably a final version a few days later.

**Comment by reevejd** [comment]
JupyterLab 3 is now supported. You can try it out with:
```bash
pip install jupyterlab-s3-browser==0.8.0
```
