### ISSUE TITLE
Unable to see any objects in S3 (possibly problem with configuration)

### ISSUE THREAD

**Issue by bkahloon** [IBM/jupyterlab-s3-browser#51]
**Describe the bug**

Hi, this might not be a bug but rather me configuring the extension improperly but I'm unable to see any objects under the bucket icon (once clicked). I do see the following error message in the logs

```console
404 GET /jupyterlab_s3_browser/auth?163007 (xx.xx.xxx.xxx) 19.64ms referer=http://localhost:9999/lab
```

**To Reproduce**

1. Installed `jupyterlab-s3-browser` (for jupyter lab 3) following the instructions in the main readme
2. Refreshed AWS credentials (have a ~/.aws/credentials file available and also tried setting the values via env variables) 
3. Click on the bucket icon in the jupyter lab UI (saw no prompt come up to enter aws credentials), but see no objects or any errors
4. Looked in the logs for jupyter lab and saw the error mentioned above (404 error)

**Expected behavior**

Expected to be able to see objects in S3 (at least the ones in the AWS account for which the credentials were configured)

**Screenshots**

![image](https://user-images.githubusercontent.com/42993708/132161108-ff845dbd-b1ed-413e-a275-92217f5f828b.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.5 LTS
- Browser: Chrome
- Version of `jupyterlab-s3-browser` extension: 0.10.1

**Comment by bkahloon** [comment]
Was able to resolve

**Comment by gopesh1992** [comment]
@bkahloon, can you pls explain how did you fix this issue, I am also facing similar issues. I have configured S3 browser in Jupyterlab as per given instructions in IBM/jupyterlab-s3-browser and set below three environment variables ,

export JUPYTERLAB_S3_ENDPOINT="https://s3.us.cloud-object-storage.appdomain.cloud"
export JUPYTERLAB_S3_ACCESS_KEY_ID="my-access-key-id"
export JUPYTERLAB_S3_SECRET_ACCESS_KEY="secret"

But I cant see the buckets when I click on S3 bucket icon in jupyterlab.
FYI, used aws service account has all permission to access S3 bucket.

**Comment by bkahloon** [comment]
oh, can you click on the folder icon instead and see if that helps. I ended up using a different extention (s3contents) for my use case if that helps

**Comment by gopesh1992** [comment]
@bkahloon , Folder icon does contain files that I have created like - notebook, text file etc..
