### ISSUE TITLE
Viewing a bucket with a large number of files/prefixes causes the extension to choke

### ISSUE THREAD

**Issue by reevejd** [IBM/jupyterlab-s3-browser#7]
Viewing a bucket with 500+ (exact number required to reproduce is unknown) items causes the extension to reliably choke.

**Comment by tomcatlingcma** [comment]
+1 to this issue. Would love to use this extension but it gets destroyed by our bucket, which has millions of objects. 

I think this could probably be solved by using 

```python
objects = list(bucket.objects.filter(Prefix=path, Delimiter='/'))
```

at https://github.com/IBM/jupyterlab-s3-browser/blob/6c9693803650864c3922c76b0413d54b42e93825/jupyterlab_s3_browser/__init__.py#L181

**Comment by brl0** [comment]
In addition to the extension choking, it seems to choke an entire jupyterlab session.

**Comment by reevejd** [comment]
I believe this was fixed in https://github.com/IBM/jupyterlab-s3-browser/pull/14, but please reopen if you're still having issues.
