### ISSUE TITLE
Consider updating s3fs version pin?

### ISSUE THREAD

**Issue by rabernat** [IBM/jupyterlab-s3-browser#71]
**Is your feature request related to a problem? Please describe.**

In https://github.com/pangeo-data/pangeo-docker-images/pull/309 we are trying to build a docker image that contains this extension, plus a lot of other packages. Currently this package pins `s3fs==2021.10.1`

https://github.com/IBM/jupyterlab-s3-browser/blob/2604cf09818c0bc15d980038e38fc22f2320adfc/setup.py#L97

That hard version pinning makes it difficult to solve our environment.

**Describe the solution you'd like**

Could you consider updating the version to `s3fs>=2021.10.1`?

Is there a reason for pinning to this specific version? We would be happy to work with the s3fs maintainers to resolve any upstream issues that led to pinning this version.

**Describe alternatives you've considered**

For us, the alternative is probably just not to use this extension.

**Comment by rabernat** [comment]
Hi folks! I'm following up on this issue. Have you had time to consider this request. Would you be open to a PR to make this change? Can anyone (maybe @reevejd) explain why s3fs is pinned?

**Comment by reevejd** [comment]
Hi @rabernat, sorry for the lack of response. I don't think there's a good reason for the s3fs pin. Please do open a PR, thanks!

**Comment by reevejd** [comment]
@rabernat FYI this was released in https://github.com/IBM/jupyterlab-s3-browser/releases/tag/0.12.0
